// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdR_xK1Kr09vr_9Nq1iQ9d5hbd41sdzZQ',
    appId: '1:63343019302:web:2d1e6f144f6f563deeede7',
    messagingSenderId: '63343019302',
    projectId: 'watsappchatscreen',
    authDomain: 'watsappchatscreen.firebaseapp.com',
    storageBucket: 'watsappchatscreen.firebasestorage.app',
    measurementId: 'G-YXGFRLZVMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUsSNfu1O9fv0i0rGHNwgKyd0OyuOYjQ',
    appId: '1:63343019302:android:e450c44300c33718eeede7',
    messagingSenderId: '63343019302',
    projectId: 'watsappchatscreen',
    storageBucket: 'watsappchatscreen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmEDg769l3B6TJZVVC5xLJIJ1Kbqu9-g',
    appId: '1:63343019302:ios:65cff8fdf76aed24eeede7',
    messagingSenderId: '63343019302',
    projectId: 'watsappchatscreen',
    storageBucket: 'watsappchatscreen.firebasestorage.app',
    iosBundleId: 'com.example.watsappchatscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVmEDg769l3B6TJZVVC5xLJIJ1Kbqu9-g',
    appId: '1:63343019302:ios:65cff8fdf76aed24eeede7',
    messagingSenderId: '63343019302',
    projectId: 'watsappchatscreen',
    storageBucket: 'watsappchatscreen.firebasestorage.app',
    iosBundleId: 'com.example.watsappchatscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdR_xK1Kr09vr_9Nq1iQ9d5hbd41sdzZQ',
    appId: '1:63343019302:web:8632299c499b5a3ceeede7',
    messagingSenderId: '63343019302',
    projectId: 'watsappchatscreen',
    authDomain: 'watsappchatscreen.firebaseapp.com',
    storageBucket: 'watsappchatscreen.firebasestorage.app',
    measurementId: 'G-BXW0GZ9RLE',
  );
}
